name: biar-project

services:
  postgres:
    image: postgres:16-alpine
    container_name: biar-database
    environment:
      POSTGRES_DB: biar
      POSTGRES_USER: biar
      POSTGRES_PASSWORD: biar_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biar"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: biar-backend
    container_name: biar-back
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biar
      SPRING_DATASOURCE_USERNAME: biar
      SPRING_DATASOURCE_PASSWORD: biar_dev
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: BVc0W2rZ4sxWxKJKuG4EgG50LGRDHkSSb3mcoU+o9zk=
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: biar-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@biar.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    image: biar-front
    container_name: biar-front
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
