name: biar-project

services:
  postgres:
    image: postgres:16-alpine
    container_name: biar-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: biar
      POSTGRES_USER: biar
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biar"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

  backend:
    image: biar-backend
    container_name: biar-back
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biar
      SPRING_DATASOURCE_USERNAME: biar
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
      APP_EXPORTS_DIR: /data/exports
    volumes:
      - exports_data:/data/exports
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G

  pgadmin:
    image: dpage/pgadmin4:9.2
    container_name: biar-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    build: ./frontend
    image: biar-front
    container_name: biar-front
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data:
  exports_data:
